"""Pydantic data contracts persisted by the distillation factory."""

from datetime import datetime, timezone

from pydantic import BaseModel, Field


def utc_now() -> datetime:
    """Return a timezone-aware timestamp for persisted records."""
    return datetime.now(timezone.utc)


class InputRecord(BaseModel):
    """A test question that should be answered by teacher and student."""

    id: str
    question: str
    created_at: datetime = Field(default_factory=utc_now)


class OutputRecord(BaseModel):
    """An answer generated by either the teacher or student."""

    input_id: str
    output: str
    source: str
    model: str | None = None
    created_at: datetime = Field(default_factory=utc_now)


class ComparisonRecord(BaseModel):
    """A judge model's structured comparison of two answers."""

    input_id: str
    winner: str
    score: float | None = None
    reason: str
    judge_model: str
    created_at: datetime = Field(default_factory=utc_now)


class JudgeResult(BaseModel):
    """Expected JSON payload returned by the judge model."""

    winner: str
    score: float | None = None
    reason: str
